defaults:
    - override hydra/launcher: submitit_local

# environment
task: walker_walk_standing
obs: state

# evaluation
checkpoint: ''
# 検証の際に実行するエピソード数
eval_episodes: 10

# 検証するステップ数の頻度
eval_freq: 5000

# training
steps: 100_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: ver2.6_tdmpc_noise_0.3
data_dir: ???
eval_threshold: 950
add_noise_step: 40000
save_model_step: 80000
obs_noise_scale: 0.3
latent_noise_scale: 0
cpg_noise_scale: 0

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# CPG
use_cpg: true
K: 1
wave_base_num : 5
time_step: 0.01
omega_bias: 18.84
omega_scale: 6.28
cpg_mlp_dim: 128

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4
cpg_entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 256
# 次元膨らませすぎ 10とかでもwalker_walkで十分では？
# 100ぐらいでいい
latent_dim: 64
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: cpg_tdmpc2
wandb_entity: hayabusa1228
wandb_name: ver2.6_tdmpc_noise_0.3_
wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: true
save_agent: true
seed: 8

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???

# evaluation
noise_scale: 0.6








